
project_id = "ufwlnoennalhfyvgeidl"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[[edge_functions.function]]
name = "create-checkout"
verify_jwt = true

[[edge_functions.function]]
name = "verify-payment"
verify_jwt = true
